### ISSUE TITLE
Enable Sleep Mode

### ISSUE THREAD

**Issue by thebao1992** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#1]
Enable Sleep Mode (S3) for DU99D4 v1.31 
When i press sleep button in Windows, mainboard goes to sleep but when i wake it up, it just show B7 code then can't resume.
Can you enable this feature inside BIOS?

**Comment by jwagnervaz** [comment]
These chienese Motherboards have sleep broken, it could be drivers or hardware.

But its one of my goals to find out a way to fix ir or have at least a awnser.

Thanks for posting. Share here, your pbc version and your setup configs.

**Comment by jwagnervaz** [comment]
Its seems Sleep works on Bios level. But when pc comes to sleep level, the 1.2v is cut down, so ram lost they power. And u cant come back from sleep.
