### ISSUE TITLE
Issue in boot with nvme ssd

### ISSUE THREAD

**Issue by dialdhruv** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#10]
After update to latest.
Nvme ssd is showing in nvme configuration
But nvme ssd not showing in boot option.

**Comment by jwagnervaz** [comment]
> After update to latest.
> Nvme ssd is showing in nvme configuration
> But nvme ssd not showing in boot option.
> 

Reinstall windows or change im bios csm support enable.

**Comment by dialdhruv** [comment]
When I tried to install new windows from bootable pendrive.

Process stuck.

When I click on boot from pendrive. Windows logo appears then after process stuck. I can not go after this process.

I have changed pendrive and download new windows image but same issue.

**Comment by dialdhruv** [comment]
Set


I have set 

Network
Storage
Video
Other PCI devices

As Legacy

Now I can not able to go to  bios setting. When turn on computer. Below message show.
![IMG20240331154817](https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/assets/53616289/bb732d1a-1619-41de-b461-ed23e436bcb9)

![IMG_20240331_154734](https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/assets/53616289/96236e60-23c5-4f62-bbe6-71a12f69cf54)


When I press shift F10 I got below details on screen. Now what can I do?
![IMG20240331154830](https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/assets/53616289/0d9f54d5-cd5c-436d-aa0a-cea85bfa8c00)

**Comment by jwagnervaz** [comment]
Enter bios press F9, after F10 and hit enter. This will restore defaults of the BIOS. 
If your nvme don't work, you can try a HDD or SSD Sata with windows, boot and restore your own BIOS.

**Comment by dialdhruv** [comment]
I have restored new bios with ch341a
My board is v1.31
And all problem solved.
In this link to program with ch340a.

ZX-DU99D4 V1.31.rom is not working and my mother board is dead

MICROCODE38REBARONUEFIFIX.ROM is working fine

https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/BIOS%20DUMP%20FOR%20FLASH%20WITH%20CH341A



In the latest firmware

https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/LASTEST

 there is bug. After update latest firmware. It stuck at windows logo. While I am able to install ubantu.


I have tried with CSM enable and disable but in both case windows install stuck at windows logo.

Need to fix bug.

Thanks



My last question is I want to upgrade my bios because my motherboard was not boot when I use 3200mhz RAM. CAN  I Use 3200mhz ram in this motherboard?

**Comment by jwagnervaz** [comment]
> I have restored new bios with ch341a
> My board is v1.31
> And all problem solved.
> In this link to program with ch340a.
> 
> ZX-DU99D4 V1.31.rom is not working and my mother board is dead
> 
> MICROCODE38REBARONUEFIFIX.ROM is working fine
> 
> https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/BIOS%20DUMP%20FOR%20FLASH%20WITH%20CH341A
> 
> 
> 
> In the latest firmware
> 
> https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/LASTEST
> 
>  there is bug. After update latest firmware. It stuck at windows logo. While I am able to install ubantu.
> 
> 
> I have tried with CSM enable and disable but in both case windows install stuck at windows logo.
> 
> Need to fix bug.
> 
> Thanks
> 
> 
> 
> My last question is I want to upgrade my bios because my motherboard was not boot when I use 3200mhz RAM. CAN  I Use 3200mhz ram in this motherboard?

Yes u can use 3200mhz server ram on this motherboard, but the clock will be limited to your cpu support.

I think the problem is just above 4g support from your gpu side. Turn off it will make your mobo boot into windows.

**Comment by dialdhruv** [comment]
i am using this ram but it is not working in it.

https://www.amazon.in/gp/product/B07W8ZDDKT/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1

is there any chance of working of this RAM?

**Comment by jwagnervaz** [comment]
> i am using this ram but it is not working in it.
> 
> https://www.amazon.in/gp/product/B07W8ZDDKT/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
> 
> is there any chance of working of this RAM?

This desktop ram stick may only works with a V3 xeon. If not .
It's not compatible with x99 chipsets.

**Comment by dialdhruv** [comment]
Any ddr4 ram 2133 mhz will work with this cpu. 
Am I right?
No matter it's ECC or regular.

**Comment by jwagnervaz** [comment]
> Any ddr4 ram 2133 mhz will work with this cpu. 
> Am I right?
> No matter it's ECC or regular.

Xeon V3 max 2133 mhz  Xeon V4 2400 MHz

But any 3200 mhz Ram ecc server or desktop would work if V3 if compatible.
I had desktop ram 3200 MHz working with 2x 2680 V4. 
Só there's some rule for ram x99. There's a lot os info out there.

**Comment by dialdhruv** [comment]
I have not received any manual with my purchase. Can I get manual for ZX-DU99D4 V1.31
