### ISSUE TITLE
error 67

### ISSUE THREAD

**Issue by BUGS-x-BUNNY** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#11]
get error 67. tried to press power button intill the PC turn off.  but the error is still 67
either the procedure was described incorrectly, or I did something wrong, or the motherboard did not eat this BIOS.

**Comment by jwagnervaz** [comment]
> get error 67. tried to press power button intill the PC turn off.  but the error is still 67
> either the procedure was described incorrectly, or I did something wrong, or the motherboard did not eat this BIOS.
>  

Ar u using which version of cpu ? Try to clear cmos and it will boot .

**Comment by BUGS-x-BUNNY** [comment]
I thought for a long time what the problem could be
tried many bios
please write down for others, in rare cases turning off the power to one of the processors helps
I tried to clean cmos, and it was definitely cleaned(it was a special start) 
just after resetting cmos you need to turn off the power to one of the processors, wait for it to load, then you can connect the entire setup
