### ISSUE TITLE
Turn on when power on.

### ISSUE THREAD

**Issue by dialdhruv** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#12]
In many bios I have seen options to 
"Restore on AC power Loss"

I am using as server so if power cut off and back then then it not turn it on, in bios I did not get option for this.

Is that any chance to turn computer on when power on?

**Comment by jwagnervaz** [comment]
The board has jumper to turn on with power, so use it.

**Comment by jwagnervaz** [comment]
The board has jumper to turn on with ac power, so use it.

**Comment by dialdhruv** [comment]
Ok thanks it's working fine.
