### ISSUE TITLE
The screen freezes when loading windows

### ISSUE THREAD

**Issue by chuss58** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#14]
The screen freezes when loading windows.

I can access the bios without problems, the problem is that windows does not start.

**Comment by jwagnervaz** [comment]
Hi, Checkout this

https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/issues/6
