### ISSUE TITLE
B7 after flashing

### ISSUE THREAD

**Issue by thiagoretes** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#15]
Hello ;)
After I flashed your latest version I got a b1 code. After holding power down button as you said and restarting I always get B7.
But it's not the usual B7 I used to get during memory check, it's B7 after 4F code.
Already tried flashing the stock version with ch341 and no success at all.
Tried removing one CPU and all ram modules, no success.
Tried booting without battery, tried reseting cmos, nothing seems to solve it ;(
Before flashing the first time I made sure my GPU supported UEFI, the GPU has a switch when toggled/untoggled it switch uefi mode or not, my GPU is a Sapphire RX 580 2GB.
Both CPUs are 2680v4
Any tips to solve this?

**Comment by jwagnervaz** [comment]
Hi, If you using 2 CPUs, install only CPU 1 for now and try to boot.




To flash via ch341 you need be sure the board is receiving Power 
So, plug the ch341 clip to the BIOS chip.

Power on the PC when try to read/flash the BIOS chip.
 

Be sure to pin 1 from BIOS match to pin 1 to clip.

Flash your stock BIOS, or my stock BIOS 


- to flash your can use any ch341 Tool like asprogrammer for exemple.
 Erase the chip and than flash your backup BIOS.

After try to boot.


If you dont have backup you can use  this original BIOS .

**Comment by thiagoretes** [comment]
It's reading, writing and verifying the ROM 'correctly' at least the checksums match. Did you mean I have to flash with PSU connected and powered? I might just give another try right now but I tried it earlier.

**Comment by thiagoretes** [comment]
Did it again with PSU connected and motherboard energized, no post. Still B7 after 4F.

**Comment by jwagnervaz** [comment]
> Did it again with PSU connected and motherboard energized, no post. Still B7 after 4F.

You need to erase chip 1st
Maybe ia Just that. You rev of the board is 1.31?

**Comment by thiagoretes** [comment]
Good news!
After rewriting lots of bios and being frustated I found a russian forum discussion about support on XM25QH128C chip, it was some guy trying to flash older bioses versions on this rev 1.31 and his problem was this chip specifically.
After downloading a full dump from another website I just checked it had this chip listed in the descriptors of the bios using UEFITool.

I checked the stock ROM you provided and it's probably this problem, it doesn't support this chip.
This is the descriptor region of the new bios I found and finally was able to boot my system:
`Fixed: Yes
Base: 0h
Address: FF000000h
Offset: 0h
ReservedVector:
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
Full size: 1000h (4096)
ME region offset: 1000h
BIOS region offset: 800000h
Region access settings:
BIOS: FFh FFh ME: FFh FFh
GbE:  FFh FFh
BIOS access table:
      Read  Write
Desc  Yes   Yes 
BIOS  Yes   Yes
ME    Yes   Yes 
GbE   Yes   Yes 
PDR   Yes   Yes 
Flash chips in VSCC table:
1F4700 (Atmel AT25DF321)
EF3016 (Winbond W25X32)
BF2541 (Microchip SST25VF016B)
1F4700 (Atmel AT25DF321)
1F4501 (Atmel AT26DF081A)
1F4600 (Atmel AT26DF161)
C22014 (Macronix MX25L80)
C22015 (Macronix MX25L16)
C22016 (Macronix MX25U16)
C22017 (Macronix MX25L64)
C22018 (Macronix MX25L128)
9D7F7A (Unknown 009D7F7Ah)
BF258E (Microchip SST25VF080B)
BF2541 (Microchip SST25VF016B)
208015 (Micron M25PE16)
EF3014 (Winbond W25X80)
EF3016 (Winbond W25X32)
EF3017 (Winbond W25X64)
EF4017 (Winbond W25Q64)
EF4018 (Winbond W25Q128)
EF6017 (Winbond W25Q64)
EF6018 (Winbond W25Q128)
C22018 (Macronix MX25L128)
A12818 (Unknown 00A12818h)
**204018 (Micron XM25QH128C)**`

This was yours stock rom:
`Fixed: Yes
Base: 0h
Address: FF000000h
Offset: 0h
ReservedVector:
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
Full size: 1000h (4096)
ME region offset: 1000h
BIOS region offset: 800000h
Region access settings:
BIOS: FFh FFh ME: FFh FFh
GbE:  FFh FFh
BIOS access table:
      Read  Write
Desc  Yes   Yes 
BIOS  Yes   Yes
ME    Yes   Yes 
GbE   Yes   Yes 
PDR   Yes   Yes 
Flash chips in VSCC table:
1F4700 (Atmel AT25DF321)
EF3016 (Winbond W25X32)
BF2541 (Microchip SST25VF016B)
1F4700 (Atmel AT25DF321)
1F4501 (Atmel AT26DF081A)
1F4600 (Atmel AT26DF161)
C22014 (Macronix MX25L80)
C22015 (Macronix MX25L16)
C22016 (Macronix MX25U16)
C22017 (Macronix MX25L64)
C22018 (Macronix MX25L128)
9D7F7A (Unknown 009D7F7Ah)
BF258E (Microchip SST25VF080B)
BF2541 (Microchip SST25VF016B)
208015 (Micron M25PE16)
EF3014 (Winbond W25X80)
EF3016 (Winbond W25X32)
EF3017 (Winbond W25X64)
EF4017 (Winbond W25Q64)
EF4018 (Winbond W25Q128)
EF6017 (Winbond W25Q64)
EF6018 (Winbond W25Q128)
C22018 (Macronix MX25L128)
1C4018 (Unknown 001C4018h)`

Perhaps it'd be nice to make some disclaimer so ppl could check if their bios chip is compatible before getting into a lot of trouble.
[This is the BIOS that finally worked, just in case you want to make your mods for it: fullbackup_301123_171936.zip](https://github.com/user-attachments/files/15930100/fullbackup_301123_171936.zip)

**Comment by jwagnervaz** [comment]
I conducted some investigation and found that the BIOS you sent is (10/30/2023) ZX-DU99D4 V1.3 DU994305, whereas mine is older (05/06/2023) ZX-DU99D4 DU994304.

As you can see, the factory keeps changing BIOS chips to generic ones and updates the VSCC table whenever they make changes in their factory. This unpredictability makes it difficult for me to anticipate their next steps.

I've advised people to back up their BIOS using a disclaimer. This way, they can return to the stock version if necessary. My goal is to fix some bugs and improve its performance.

I'll include this information in the readme soon and suggest that people post their own BIOS here before flashing, so we can verify the BIOS information.

Regarding AFUWIN, I'll try to create a tutorial. I suggested AFUWIN because FTP doesn't support these counterfeit BIOS chips that the factory uses.

As you can see, the factory continues to "update" this BIOS, and there's a newer BIOS (2024 build) available. I saw it in a video and asked the person to share it, but unfortunately, he gave me an empty response.

https://www.youtube.com/watch?v=_TRXTacvTdU


I don't personally know anyone in the manufacturing process. This board is sold by various Chinese brands, and support for it is uncertain.

**Comment by jwagnervaz** [comment]
@thiagoretes  Did test your bios that was posted here https://xeon-e5450.ru/socket-2011-3/kllisre-x99-dual-zx-du99d4-v1-11/
and it gave me error b7. 
so it confirms that is about VSCC table.
will try to make this version universal for older boards.

**Comment by thiagoretes** [comment]
This was my original bios in case you want: [stockbios.zip](https://github.com/user-attachments/files/16059671/stockbios.zip)
The most useful information I found about this board were on this topic: https://forums.overclockers.ru/viewtopic.php?p=18099360#p18099360

**Comment by jwagnervaz** [comment]
> This was my original bios in case you want: [stockbios.zip](https://github.com/user-attachments/files/16059671/stockbios.zip)
> The most useful information I found about this board were on this topic: https://forums.overclockers.ru/viewtopic.php?p=18099360#p18099360

Thanks for your dump, I just find out you have the lastest bios available, so it's just not about IC  support table, something was changed in motherboard, making older bios incompatible. Your bios give me error B7 to, will investigate more and return with more data. 

You help a lot today, once again thanks .

**Comment by jwagnervaz** [comment]
@thiagoretes  I did a port to older boards version (4304 and older) thanks to your dump. so thanks a lot for helping the comunity. 

soon i will do mod to 4305 and newer board versions.

as i dont have this new board, i cant check if have bugs or need any fix.

**Comment by thiagoretes** [comment]
When it's done feel free to ping me, I can test it on my board. ;)

**Comment by jwagnervaz** [comment]
@thiagoretes  hi, hope you well, can you test if EFI shell launch works in your factory bios ? It's a boot option of the bios.
I just wanna check if it's a problem of the lastest bios or my port get some random issue.

Thanks a lot since now.

**Comment by proton555** [comment]
> @thiagoretes hi, hope you well, can you test if EFI shell launch works in your factory bios ? It's a boot option of the bios. I just wanna check if it's a problem of the lastest bios or my port get some random issue.
> 
> Thanks a lot since now.
Hello jwagnervaz for helping the community
1. I have recently got one of these dual boards model name ZX-DU99D4 V1.31. I have the latest bios dump via both FPT (16MB) and AFU(8MB). Should i post here? 
2. Can latest bios be improved?
3. I have a 26** v4 but unfortunately there is no way to overclock it. Is that right? no way?
4. I plan to buy a 26** v3 and turboboost them, will it work with newest default bios or can you help me? :)
Thanks again

**Comment by jwagnervaz** [comment]
> > @thiagoretes hi, hope you well, can you test if EFI shell launch works in your factory bios ? It's a boot option of the bios. I just wanna check if it's a problem of the lastest bios or my port get some random issue.
> > 
> > Thanks a lot since now.
> 
> Hello
> Thanks jwagnervaz for helping the community
> 1. I have recently got one of these dual board
> model name ZX-DU99D4 V1.31
> Bios Version DU994 3.06 x64
> Flash Device : MX25L12875F
> 2. I have the latest bios dump via both FPT (16MB) and AFU(8MB). Should i send you?  will it help community?
> 2. Can latest bios be improved?
> 3. I have a 26** v4 but unfortunately there is no way to overclock it. Is that right? no way?
> 4. Do 26** v3 get turboboost unlock by default with latest BIOS or needs editing from you? can you help? :)
> Thanks again
> 

Hi, sure if you can sent the bios files would help others.
As you can see my board rev is same but hardware is different. 
Soon as possible I will mod this boards with bios 3.05 or higher.

V4 don't need unlock turbo boost, an 2670 v3 with turbo boost unlocked lost in performance for an 2680 v4 stock.

V3 it's nos efficient due the 22nm vs 14nm of V4. 


Bios need mods to support v3 unlock turbo. 
But I don't recommend, it much better use an 2689 v4 stock for temps

It's a board with dual CPU. So stress VRM it's not a good idea.

**Comment by jwagnervaz** [comment]
> Were do i send the bios file? Do you have an email or telegram?
> 
Here in github you can send files


> But 2696 v3 overclocked has 25% more performance than 2696 v4. I checked


Check it again

https://valid.x86.fr/3azls8
2697 v3 unlock turbo boost

Source 
https://www.reddit.com/r/overclocking/comments/r1hrsr/squeezing_out_everything_from_old_intel_xeon/?rdt=52331


https://valid.x86.fr/k7ez9k
2697 v4 stock


> Yes true that they are less efficient, we can add extra heatsink to VRM. I have good watercooling

WC its good to cpu, and very bad to VRM

> So can you confirm that other than help of v3 turbo unlock, there is no use of this biosmod for v4 processors?

I had achieved a pseudo turbo with some bios mod, but VRM will be damaged due no good VRM for Dual CPU  

> Can we overclock v4 any other way except increasing little busspeed?
In theory yes but 105 seems to be the high on most cpus.

**Comment by thiagoretes** [comment]
> @thiagoretes hi, hope you well, can you test if EFI shell launch works in your factory bios ? It's a boot option of the bios. I just wanna check if it's a problem of the lastest bios or my port get some random issue.
> 
> Thanks a lot since now.
> 
> Edit: I did test 3 factory bios and this option does not work, I never tried before, so I dont know if it's really ever worked.
> 
> Edit2: I did test all factory versions I have, none of them works built in shell EFI boot option, so I can confirm it's a bug from factory . Will try to fix.
> 
> Edit2: bug present in all DU99D4 fixed, I find the error and fixed, will release a new bios soon with EFI Built-in Shell 2.2 Edk2 24H1.
> 
> Thanks a lot.

Long time without checking my mentions haha.
Do you still need me to test it?

**Comment by jwagnervaz** [comment]
> > @thiagoretes hi, hope you well, can you test if EFI shell launch works in your factory bios ? It's a boot option of the bios. I just wanna check if it's a problem of the lastest bios or my port get some random issue.
> > 
> > Thanks a lot since now.
> > 
> > Edit: I did test 3 factory bios and this option does not work, I never tried before, so I dont know if it's really ever worked.
> > 
> > Edit2: I did test all factory versions I have, none of them works built in shell EFI boot option, so I can confirm it's a bug from factory . Will try to fix.
> > 
> > Edit2: bug present in all DU99D4 fixed, I find the error and fixed, will release a new bios soon with EFI Built-in Shell 2.2 Edk2 24H1.
> > 
> > Thanks a lot.
> 
> Long time without checking my mentions haha.
> Do you still need me to test it?

Thanks a lot but I already test

**Comment by proton555** [comment]
> Here in github you can send files
attached https://we.tl/t-nhXgmgyu5m

> Check it again
> https://valid.x86.fr/3azls8 2697 v3 unlock turbo boost
> https://valid.x86.fr/k7ez9k 2697 v4 stock
I messed the cpu models. nevermind
 
> I had achieved a pseudo turbo with some bios mod, but VRM will be damaged due no good VRM for Dual CPU
Can you help me a bit trying this pseudo turbo. I have extra heatsinks installed on VRM and also have external temperature sensors, i would like to try? We can test or discuss i private, if you like.

**Comment by proton555** [comment]
> Here in github you can send files

attached https://we.tl/t-nhXgmgyu5m

>Check it again
>https://valid.x86.fr/3azls8 2697 v3 unlock turbo boost
>https://valid.x86.fr/k7ez9k 2697 v4 stock

I messed the cpu models. nevermind

>I had achieved a pseudo turbo with some bios mod, but VRM will be damaged due no good VRM for Dual CPU

Is that using bios mods? pseudo meaning non-constant turbo? Can you help me a try? I have extra heatsinks installed on VRM and also have external temperature sensors. We can test or discuss i private, if you like.

**Comment by proton555** [comment]
@jwagnervaz All fine? did you get the file? i did not hear back

**Comment by jwagnervaz** [comment]
> @jwagnervaz All fine? did you get the file? i did not hear back. thanks
> 

Yes your bios is the same as @thiagoretes , I'm working in a mod for bioses newer than DU994305

Currently  my mods is compatible only with DU994304 and older bios versions.

Factory has changed the motherboard components on DU994305 board and newer.
