### ISSUE TITLE
Newer Bios base version

### ISSUE THREAD

**Issue by J0SH1X** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#18]
I recently got this mainboard and my bios is actually newer then the latest one here

Dumped with flashrom on linux and reflashed to the chip to verify

[bios.zip](https://github.com/user-attachments/files/17528041/bios.zip)

**Comment by jwagnervaz** [comment]
Thanks for your contribution

Will check for fix and bugs and update if needed.

**Comment by J0SH1X** [comment]
Where did you get a 2024 bios if my board has a newer revision

Wagner ***@***.***> schrieb am Sa., 26. Okt. 2024, 16:40:
