### ISSUE TITLE
What are the best options in afuwingui when installing a new biosmod?

### ISSUE THREAD

**Issue by ygyjgj** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#19]
My board: DU994 3.04 x64 (05/06/2023)

I want to install https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/PORT-VERSION-4304-OR-OLDER

What options should be selected in afuwingui?

Should the “program all blocks” option be checked?
Or select other options as well?
Is it necessary to do any additional things with ME region?

![fileafu](https://github.com/user-attachments/assets/2f1e7852-d18f-4874-b6f8-d63d827a8966)

**Comment by ygyjgj** [comment]
![afu2](https://github.com/user-attachments/assets/091f03a2-cfc6-4d73-acbe-4707806dceb6)

**Comment by ygyjgj** [comment]
I made a backup of the bios
![cmdbackup](https://github.com/user-attachments/assets/527b4813-50bc-424b-a698-d7c186162475)

**Comment by ygyjgj** [comment]
I made a backup of the bios
![cmdbackup](https://github.com/user-attachments/assets/4b92d75b-a38b-4646-9ce1-e4ebed716fb9)

**Comment by jwagnervaz** [comment]
Just click:
 


Program all blocks 
Entire

Hope you enjoy the BIOS
