### ISSUE TITLE
Error Code 79 with 2x E5-2680 V4

### ISSUE THREAD

**Issue by cowboype** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#22]
Hi there! How you doing?

I have exactly the same issue of this post - https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/issues/21

But with 2x 2680 V4 CPU. The bios is the same version 3.06. I tried to flash the biosmod newmicrocode and the issue dont solved in my case [same error code 79]. Can you help me too, pls? Thx a lot.

My stock bios - 
[ZX-DU99D4_v1.31_3.06.zip](https://github.com/user-attachments/files/17807846/ZX-DU99D4_v1.31_3.06.zip)

**Comment by cowboype** [comment]
> > Hi there! How you doing?
> > I have exactly the same issue of this post - #21
> > But with 2x 2680 V4 CPU. The bios is the same version 3.06. I tried to flash the biosmod newmicrocode and the issue dont solved in my case [same error code 79]. Can you help me too, pls? Thx a lot.
> > My stock bios -
> > [ZX-DU99D4_v1.31_3.06.zip](https://github.com/user-attachments/files/17807846/ZX-DU99D4_v1.31_3.06.zip)
> 
> Your Board boot with 1 CPU ? If not the error it's DDR4 memory.
> 
> Dont mix RAM brands and type
> 
> Theses V4 don't accept UDIMM ( Desktop memory when Dual CPU)
> 
> Send more details of your configuration.

Yes, boot with 1 cpu exactly the guy the other post. with 2 cpu 2680 v4 stops error code 79. I used desktop memory. I don´t have server memory now. So is it just boot up with desktop memory with 1 cpu? The code error would be B7 or 67 [memory error]?

**Comment by jwagnervaz** [comment]
V4 dont have support to Desktop RAM, if you use a ECC RAM will post normal.

I have 2 X 2680 v4 and it have support from stock factory bios. 
The case you pointed its not the same


 
His CPU is newer than 2680 V4 and Stock Factory Bios dont have microde that support it .


Your solution is use DDR4 ECC ( Server ) if you wanna use DUAL cpu.

**Comment by cowboype** [comment]
> V4 dont have support to Desktop RAM, if you use a ECC RAM will post normal.
> 
> I have 2 X 2680 v4 and it have support from stock factory bios. The case you pointed its not the same
> 
> His CPU is newer than 2680 V4 and Stock Factory Bios dont have microde that support it .
> 
> Your solution is use DDR4 ECC ( Server ) if you wanna use DUAL cpu.

I see now. Thanks for your help. I´ll take DDR4 ECC memories to use dual cpu.
