### ISSUE TITLE
Xeon v4 Dual

### ISSUE THREAD

**Issue by kubolowy** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#3]
Hello
I have a problem with running dual E5-2667 v4, it displays error 79
On the zx-du99d4 v1.31 board
I see on cpu-z that you managed to run V4
I currently have BIOS MOD BIOS 2400 RAM CLOCK + MICROCODE LASTEST installed
On a single processor, everything starts correctly with a working turbo boost.

**Comment by jwagnervaz** [comment]
Hi, i recomend you to flash 
https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/LASTEST

79 is related to GPU and maybe memory 
maybe you need to check your GPU, this  have UEFI boot?

You can try to erase CMOS too.

All bios i had post here will work with any V3 or V4 E5
