### ISSUE TITLE
Code 67

### ISSUE THREAD

**Issue by darivations** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#5]
hi, I updated the bios to the latest (01-DEC-23NLOGORTCME9FASTBOOTZX-DU99D41.31UEFIFIXMEUPDATE.ROM), found code 67 and cleared coms many times. There is only 1 usable RAM slot left and when I updated to the previous version that was usable, I was unable to use any other RAM slots. Now only 1 slot can be used. Can you give any advice?

**Comment by jwagnervaz** [comment]
> hi, I updated the bios to the latest (01-DEC-23NLOGORTCME9FASTBOOTZX-DU99D41.31UEFIFIXMEUPDATE.ROM), found code 67 and cleared coms many times. There is only 1 usable RAM slot left and when I updated to the previous version that was usable, I was unable to use any other RAM slots. Now only 1 slot can be used. Can you give any advice?

After get error 67 press power button till the system turn off and bios will clear cmos by itself.

**Comment by darivations** [comment]
> > hi, I updated the bios to the latest (01-DEC-23NLOGORTCME9FASTBOOTZX-DU99D41.31UEFIFIXMEUPDATE.ROM), found code 67 and cleared coms many times. There is only 1 usable RAM slot left and when I updated to the previous version that was usable, I was unable to use any other RAM slots. Now only 1 slot can be used. Can you give any advice?
> 
> After get error 67 press power button till the system turn off and bios will clear cmos by itself.
> 
> I recomend to use Winflash to update the bios.
I did what you said many times. Now it doesn't work. Winflash i used that you share. I'll keep trying.

**Comment by darivations** [comment]
I did what you said many times. Now it doesn't work. Winflash i used that you share. I'll keep trying.

**Comment by jwagnervaz** [comment]
> I did what you said many times. Now it doesn't work. Winflash i used that you share. I'll keep trying.

Whats your board rev?

**Comment by darivations** [comment]
ZX-DU99D4 v1.31

**Comment by darivations** [comment]
I tried changing the CPU to E5-2680v4, everything worked normally.

**Comment by darivations** [comment]
> > ZX-DU99D4 v1.31
> 
> Same as mine, im using this version since November, maybe reflash solve your ussue.

reflash any version e5-2699v3 can't use other ram slot. I bought this week e5-2680v4 normally use all slot.

**Comment by jwagnervaz** [comment]
> > > ZX-DU99D4 v1.31
> > 
> > Same as mine, im using this version since November, maybe reflash solve your ussue.
> 
> reflash any version e5-2699v3 can't use other ram slot. I bought this week e5-2680v4 normally use all slot.

I only tested with 2670 v3 and 2680 v4.
But it could be a lot of things.

Happy 2680 v4 worked for you.
