### ISSUE TITLE
Stuck on Windows loading screen

### ISSUE THREAD

**Issue by krygx** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#6]
Hello, I have installed the latest bios with the program (RTCFASTBOOTZX-DU99D41.31UEFIFIXMEUPDATEMICROCODENEW.ROM) and the bios works but when I boot with the hard drive with Windows 10 it gets stuck on the loading screen with the little white balls that spin and It starts to lag and then freezes.

**Comment by jwagnervaz** [comment]
Post rev of your Motherboard, check if your windows is uefi or csm. Maybe you did a csm install.

**Comment by Chip200** [comment]
Good afternoon. Motherboard zx-du99d4 v1.31
Flashed BIOS RTCFASTBOOTZX-DU99D41.31UEFIFIXMEUPDATEMICROCODENEW.ROM
When I turn on the computer I cannot get into the BIOS. Black screen, as if the video card is not connected. Windows is displayed immediately.

**Comment by jwagnervaz** [comment]
> Good afternoon. Motherboard zx-du99d4 v1.31
> Flashed BIOS RTCFASTBOOTZX-DU99D41.31UEFIFIXMEUPDATEMICROCODENEW.ROM
> When I turn on the computer I cannot get into the BIOS. Black screen, as if the video card is not connected. Windows is displayed immediately.

What gpu you using? 
Its about uefi compatibility,
Turn it on
Press del to get in bios
Press F9 and Enter
F10 and Enter.

If your gpu dont have uefi support maybe upgrade to a model thats suports can fix it.

If you boot into windows,  restore your own bios backup could be a possibility too.

**Comment by krygx** [comment]
> Post rev of your Motherboard, check if your windows is uefi or csm. Maybe you did a csm install. Reinstall windows, or search for how to converter windows legacy to windows uefi install.
> 
> Or Just set CSM support on at the bios

The QR on my motherboard says PG-00-BXDU99D4V13100100/23GB2996/1208/2606 and the text ZX-DU99D4 V1.31, my Windows 10 is CSM, I tried to run it with CSM support but happens the same, so I tried to install Windows 10 but UEFI, and even with CSM support it also freezes in the USB installation loading screen.

**Comment by jwagnervaz** [comment]
> > Post rev of your Motherboard, check if your windows is uefi or csm. Maybe you did a csm install. Reinstall windows, or search for how to converter windows legacy to windows uefi install.
> > 
> > Or Just set CSM support on at the bios
> 
> The QR on my motherboard says PG-00-BXDU99D4V13100100/23GB2996/1208/2606 and the text ZX-DU99D4 V1.31, my Windows 10 is CSM, I tried to run it with CSM support but happens the same, so I tried to install Windows 10 but UEFI, and even with CSM support it also freezes in the USB installation loading screen.

Do your see the bios screen?
If not, you need a GPU with UEFI suport
U didnt said the model of your GPU.

If u see bios screen.
Disable  
Above 4G decoding

Advanced/PCI Subsystem Settings


And enable csm support at
Advanced/CSM Configuration

Set

Network
Storage
Video
Other PCI devices

As Legacy
And try  boot windows.

**Comment by krygx** [comment]
I think it was the Above 4G Decoding, all it's working now, thank you so much.

**Comment by jwagnervaz** [comment]
> I think it was the Above 4G Decoding, all it's working now, thank you so much.

Happy you solved the problem,

above 4g decoding is supported in 99% of GPU with BIOS UEFI.
But GPU non-UEFI have blackscreen or dont iven boot If 4G on.

What is your GPU?

It could help others.
Thanks .

**Comment by krygx** [comment]
PNY XLR8 RTX 3080 10GB.

**Comment by jwagnervaz** [comment]
> PNY XLR8 RTX 3080 10GB.

This GPU is supposed to work with UEFI,  but maybe this have problems with above 4g.

**Comment by krygx** [comment]
Can I Turbo Unlock my x2 Xeon E5-2696 v3 with this bios?

**Comment by krygx** [comment]
But if I have the VRMs cold enough and I disable some cores, could I do Turbo Unlock?
