### ISSUE TITLE
Brick on ZX-DU99D4-V1.12

### ISSUE THREAD

**Issue by Aldair502** [jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD#7]
Just saying i had the same issue of #6 but after the reboot i got error code 61 and my board got bricked (i already cleared the cmos like 3 times)

I flashed https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/TOOL%20FLASH since readme said ZX-DU99D4-V1.12 is compatible.

Here a copy of my bios with afuwin
[afuwin.zip](https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/files/13971046/afuwin.zip)

Also i'm on my way to buy a Ch341 programmer

**Comment by jwagnervaz** [comment]
> Just saying i had the same issue of #6 but after the reboot i got error code 61 and my board got bricked (i already cleared the cmos like 3 times)
> 
> I flashed https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/TOOL%20FLASH since readme said ZX-DU99D4-V1.12 is compatible.
> 
> Here a copy of my bios with afuwin
> [afuwin.zip](https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/files/13971046/afuwin.zip)
> 
> Also i'm on my way to buy a Ch341 programmer

What CPU ar u using, 61 it's incompatible ram or init CPU failed.

Try to bot only with one ram stick.
E5 V4 only works with ECC ram.
E5 V3 is supposed to work with Desktops ram.

If nothing works, just flash your BIOS backup with Ch341 clip.

**Comment by Aldair502** [comment]
> > Just saying i had the same issue of #6 but after the reboot i got error code 61 and my board got bricked (i already cleared the cmos like 3 times)
> > I flashed https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/tree/main/TOOL%20FLASH since readme said ZX-DU99D4-V1.12 is compatible.
> > Here a copy of my bios with afuwin
> > [afuwin.zip](https://github.com/jwagnervaz/DUAL-CPU-ZX-DU99D4-V1.31-BIOSMOD/files/13971046/afuwin.zip)
> > Also i'm on my way to buy a Ch341 programmer
> 
> What CPU ar u using, 61 it's incompatible ram or init CPU failed.
> 
> Try to bot only with one ram stick. E5 V4 only works with ECC ram. E5 V3 is supposed to work with Desktops ram.
> 
> If nothing works, just flash your BIOS backup with Ch341 clip.

yeah I'm using just one ram stick. also a E5 V3 (E5-2690V3) then im going the backup anyways
